# File I/O

In this section, the focus is on file input and output (I/O) in PyTorch. Saving and loading individual tensors using save and load functions are explained. A list of tensors and a dictionary of tensors can also be saved and loaded. Saving and loading model parameters using state_dict and load_state_dict functions are also discussed.





In [10]:
import torch
from torch import nn
from torch.nn import functional as F

## (**Loading and Saving Tensors**)




In [11]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [12]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [13]:
y = torch.zeros(4)
torch.save([x, y],'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [14]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

## [**Loading and Saving Model Parameters**]


In [15]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.LazyLinear(256)
        self.output = nn.LazyLinear(10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [16]:
torch.save(net.state_dict(), 'mlp.params')

In [17]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): LazyLinear(in_features=0, out_features=256, bias=True)
  (output): LazyLinear(in_features=0, out_features=10, bias=True)
)

In [18]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])